function Send-DiscordReport {
    param(
        $HistoryData, 
        $PityTrackers, 
        $Config, # รับ GameConfig (Genshin/HSR/ZZZ)
        [bool]$ShowNoMode
    )
    
    # เรียกใช้ Function จาก ConfigManager เพื่อเอา Webhook URL ล่าสุด
    if (Get-Command "Get-AppConfig" -ErrorAction SilentlyContinue) {
        $CurrentAppConfig = Get-AppConfig 
        $WebhookUrl = $CurrentAppConfig.WebhookUrl
    } else {
        return "Error: ConfigManager logic not found."
    }

    if ([string]::IsNullOrWhiteSpace($WebhookUrl)) { return "Skipped (Empty Webhook URL)" }

    # สร้าง Fields แสดง Pity ปัจจุบันของแต่ละตู้
    $fields = @()
    foreach ($b in $Config.Banners) {
        $val = $PityTrackers[$b.Code]
        if ($null -eq $val) { $val = 0 }
        $fields += @{ name = "$($b.Name) Pity"; value = "**$val**"; inline = $true }
    }

    # สร้าง Description แสดงประวัติย้อนหลัง 30 รายการ
    $descTxt = ""
    $count = 0
    $limit = 30
    
    if ($HistoryData.Count -gt 0) {
        $descTxt = "**Recent History (Last $limit):**`n"
        for ($i = $HistoryData.Count - 1; $i -ge 0; $i--) {
            if ($count -ge $limit) { break }
            $h = $HistoryData[$i]
            
            # Logic สีลูกบอลตามความเกลือ
            $icon = ":green_circle:"
            if ($h.Pity -gt 75) { $icon = ":red_circle:" } elseif ($h.Pity -gt 50) { $icon = ":yellow_circle:" }
            
            # การแสดงผลแบบมีเลขลำดับ หรือ เวลา
            if ($ShowNoMode) {
                $prefix = "[No.$($i+1)]"
            } else {
                $prefix = "`[$($h.Time)`]"
            }
            
            # ตัดชื่อตู้ให้สั้นลง
            $bannerText = if ($h.Banner) { $h.Banner } else { "Unknown" }
            $bNameShort = $bannerText.Split('(')[0].Trim()
            
            $descTxt += "$prefix $icon **$($h.Name)** (Pity: **$($h.Pity)**) - *$bNameShort*`n"
            $count++
        }
    } else {
        $descTxt = "No history found."
    }

    # ประกอบร่าง JSON Payload
    $payload = @{
        username = "$($Config.Name) Tracker"
        avatar_url = $Config.IconUrl
        embeds = @(
            @{
                title = "$($Config.Name) Wish Report"
                description = $descTxt
                color = $Config.ThemeColor
                fields = @($fields)
                footer = @{ text = "Generated by Universal Hoyo Counter" }
                thumbnail = @{ url = $Config.IconUrl } 
            }
        )
    }

    try {
        # ส่งข้อมูล
        Invoke-RestMethod -Uri $WebhookUrl -Method Post -Body ($payload | ConvertTo-Json -Depth 10 -Compress) -ContentType 'application/json'
        return "Sent Successfully!"
    } catch {
        return "Failed: $($_.Exception.Message)"
    }
}