function Send-EmailReport {
    param (
        [Parameter(Mandatory=$true)] $HistoryData,
        [Parameter(Mandatory=$true)] $Config, # อันนี้คือ Config เกม (Color/Name)
        [string]$SubjectPrefix = "Gacha Report"
    )

    # =========================================================
    # 1. LOAD APP CONFIG (จากไฟล์ JSON โดยตรง)
    # =========================================================
    
    # หา Path: ถอยจาก Engine ออกมา 1 ขั้น -> เข้า Settings -> config.json
    $RootPath = Split-Path $PSScriptRoot -Parent
    $JsonPath = Join-Path $RootPath "Settings\config.json"

    if (-not (Test-Path $JsonPath)) {
        Write-Host "[EmailManager] Error: Config file not found at $JsonPath" -ForegroundColor Red
        return $false
    }

    try {
        # อ่านไฟล์ JSON สดๆ (จะได้ค่าล่าสุดเสมอ)
        $AppConf = Get-Content $JsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        Write-Host "[EmailManager] Error reading config.json" -ForegroundColor Red
        return $false
    }

    # =========================================================
    # 2. VALIDATE SETTINGS
    # =========================================================
    $toEmail = $AppConf.NotificationEmail
    $senderEmail = $AppConf.SenderEmail
    $senderPass  = $AppConf.SenderPassword

    if ([string]::IsNullOrWhiteSpace($toEmail)) {
        # ถ้าไม่มีคนรับ ก็จบเลย (เงียบๆ)
        return 
    }

    if ([string]::IsNullOrWhiteSpace($senderEmail) -or [string]::IsNullOrWhiteSpace($senderPass)) {
        # ถ้าไม่มีคนส่ง แจ้งเตือนหน่อย
        if (Get-Command "WriteGUI-Log" -ErrorAction SilentlyContinue) {
            WriteGUI-Log "Email Error: Sender Email or Password not set in config.json" "Red"
        } else {
            Write-Host "Email Error: Missing Sender Config" -ForegroundColor Red
        }
        return $false
    }

    # ค่า Default ถ้าใน JSON ไม่ได้ใส่มา
    $smtpServer = if ($AppConf.SmtpServer) { $AppConf.SmtpServer } else { "smtp.gmail.com" }
    $smtpPort   = if ($AppConf.SmtpPort)   { $AppConf.SmtpPort }   else { 587 }

    # =========================================================
    # 3. GENERATE HTML (Gaming Style)
    # =========================================================
    $style = @"
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #1e1e1e; color: #e0e0e0; }
        .container { width: 100%; max-width: 600px; margin: 0 auto; background-color: #2d2d2d; padding: 20px; border-radius: 8px; border: 1px solid #444; }
        .header { text-align: center; border-bottom: 2px solid $($Config.AccentColor); padding-bottom: 15px; margin-bottom: 20px; }
        .header h2 { color: $($Config.AccentColor); margin: 0; text-transform: uppercase; letter-spacing: 2px; }
        .meta { background-color: #383838; padding: 12px; border-radius: 4px; margin-bottom: 20px; font-size: 13px; color: #ccc; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { text-align: left; padding: 10px; background-color: #333; color: #888; border-bottom: 1px solid #555; font-size: 12px; text-transform: uppercase; }
        td { padding: 10px; border-bottom: 1px solid #333; font-size: 14px; }
        .highlight { color: #FFD700; font-weight: bold; text-shadow: 0 0 5px rgba(255, 215, 0, 0.3); } /* 5-Star Glow */
        .pity { color: #00fa9a; font-weight: bold; }
        .footer { margin-top: 25px; font-size: 11px; color: #555; text-align: center; border-top: 1px solid #333; padding-top: 10px; }
    </style>
"@

    $rows = ""
    foreach ($item in $HistoryData) {
        $rows += "<tr>
            <td>$($item.Time)</td>
            <td class='highlight'>$($item.Name)</td>
            <td class='pity'>$($item.Pity)</td>
            <td>$($item.Banner)</td>
        </tr>"
    }

    $gameName = if ($script:CurrentGame) { $script:CurrentGame } else { "Gacha Game" }

    $htmlBody = @"
    <html>
    <head>$style</head>
    <body>
        <div class='container'>
            <div class='header'>
                <h2>$gameName Report</h2>
            </div>
            <div class='meta'>
                <strong>Items Found:</strong> $($HistoryData.Count)<br>
                <strong>Timestamp:</strong> $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
            </div>
            <table>
                <tr><th>Time</th><th>Character / Weapon</th><th>Pity</th><th>Banner</th></tr>
                $rows
            </table>
            <div class='footer'>
                Generated by HoyoEngine v7.1.0  <a href='#' style='color:#777;text-decoration:none;'>Advanced Gacha Analytics</a>
            </div>
        </div>
    </body>
    </html>
"@

    # =========================================================
    # 4. SEND MAIL
    # =========================================================
    try {
        $secPass = ConvertTo-SecureString $senderPass -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential($senderEmail, $secPass)

        Send-MailMessage -From $senderEmail `
                         -To $toEmail `
                         -Subject "[$gameName] $SubjectPrefix ($($HistoryData.Count) Items)" `
                         -Body $htmlBody `
                         -BodyAsHtml `
                         -SmtpServer $smtpServer `
                         -Port $smtpPort `
                         -UseSsl `
                         -Credential $cred

        if (Get-Command "WriteGUI-Log" -ErrorAction SilentlyContinue) {
            WriteGUI-Log "Email Report Successfully Sent to $toEmail" "Lime"
        }
        return $true

    } catch {
        $errMsg = $_.Exception.Message
        if (Get-Command "WriteGUI-Log" -ErrorAction SilentlyContinue) {
            WriteGUI-Log "Failed to send email: $errMsg" "Red"
        } else {
            Write-Host "Failed to send email: $errMsg" -ForegroundColor Red
        }
        return $false
    }
}